version: '3.9'
services:

  user-db:
    container_name: userdb
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser", "-d", "userdb" ]
      interval: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/userdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      user-db:
        condition: service_healthy

  order-db:
    container_name: orderdb
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: orderdb
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser", "-d", "orderdb" ]
      interval: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orderdb:5433/orderdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      order-db:
        condition: service_healthy

  site-bff:
    build:
      context: .
      dockerfile: Dockerfile
      target: site-bff
    ports:
      - "8080:8080"
    environment:
      BFF_USER-SERVICE_URL: http://user-service:8081/api/users
      BFF_ORDER-SERVICE_URL: http://order-service:8082/api/orders
    depends_on:
      - user-service
      - order-service

volumes:
  user_db_data:
  order_db_data:
